services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: talkAndVote
      MYSQL_USER: admin_talkandvote
      MYSQL_PASSWORD: a123123!!
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: >
      bash -c "npm i &&
              npm run dev"
    depends_on:
      - backend
    networks:
      - my_network

volumes:
  db_data:
  redis_data:

networks:
  my_network:
    driver: bridge
